/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin/news'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedArticleArticleIdRouteImport } from './routes/_authenticated/article.$articleId'
import { Route as AuthenticatedGamesGameIdRouteImport } from './routes/_authenticated/games.$gameId'
import { Route as AuthenticatedLessonCourseIdLessonIdRouteImport } from './routes/_authenticated/lesson.$courseId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedArticleArticleIdRoute =
  AuthenticatedArticleArticleIdRouteImport.update({
    id: '/article/$articleId',
    path: '/article/$articleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGamesGameIdRoute =
  AuthenticatedGamesGameIdRouteImport.update({
    id: '/$gameId',
    path: '/$gameId',
    getParentRoute: () => AuthenticatedGamesRoute,
  } as any)
const AuthenticatedLessonCourseIdLessonIdRoute =
  AuthenticatedLessonCourseIdLessonIdRouteImport.update({
    id: '/lesson/$courseId/$lessonId',
    path: '/lesson/$courseId/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/games': typeof AuthenticatedGamesRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/shop': typeof AuthenticatedShopRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/article/$articleId': typeof AuthenticatedArticleArticleIdRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lesson/$courseId/$lessonId': typeof AuthenticatedLessonCourseIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/games': typeof AuthenticatedGamesRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/shop': typeof AuthenticatedShopRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/article/$articleId': typeof AuthenticatedArticleArticleIdRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lesson/$courseId/$lessonId': typeof AuthenticatedLessonCourseIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/games': typeof AuthenticatedGamesRouteWithChildren
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/article/$articleId': typeof AuthenticatedArticleArticleIdRoute
  '/_authenticated/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/lesson/$courseId/$lessonId': typeof AuthenticatedLessonCourseIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/games'
    | '/leaderboard'
    | '/profile'
    | '/shop'
    | '/admin/courses'
    | '/admin/news'
    | '/admin/users'
    | '/article/$articleId'
    | '/games/$gameId'
    | '/admin/'
    | '/lesson/$courseId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/games'
    | '/leaderboard'
    | '/profile'
    | '/shop'
    | '/admin/courses'
    | '/admin/news'
    | '/admin/users'
    | '/article/$articleId'
    | '/games/$gameId'
    | '/admin'
    | '/lesson/$courseId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/games'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/shop'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/users'
    | '/_authenticated/article/$articleId'
    | '/_authenticated/games/$gameId'
    | '/_authenticated/admin/'
    | '/_authenticated/lesson/$courseId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/article/$articleId': {
      id: '/_authenticated/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof AuthenticatedArticleArticleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/$gameId': {
      id: '/_authenticated/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthenticatedGamesGameIdRouteImport
      parentRoute: typeof AuthenticatedGamesRoute
    }
    '/_authenticated/lesson/$courseId/$lessonId': {
      id: '/_authenticated/lesson/$courseId/$lessonId'
      path: '/lesson/$courseId/$lessonId'
      fullPath: '/lesson/$courseId/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonCourseIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedGamesRouteChildren {
  AuthenticatedGamesGameIdRoute: typeof AuthenticatedGamesGameIdRoute
}

const AuthenticatedGamesRouteChildren: AuthenticatedGamesRouteChildren = {
  AuthenticatedGamesGameIdRoute: AuthenticatedGamesGameIdRoute,
}

const AuthenticatedGamesRouteWithChildren =
  AuthenticatedGamesRoute._addFileChildren(AuthenticatedGamesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRouteWithChildren
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedArticleArticleIdRoute: typeof AuthenticatedArticleArticleIdRoute
  AuthenticatedLessonCourseIdLessonIdRoute: typeof AuthenticatedLessonCourseIdLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRouteWithChildren,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedArticleArticleIdRoute: AuthenticatedArticleArticleIdRoute,
  AuthenticatedLessonCourseIdLessonIdRoute:
    AuthenticatedLessonCourseIdLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
